# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  # Sqlite Settings
#  adapter: jdbcmysql
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: bort_development
  username: root
  password: haxored
  pool: 5
  host: localhost
  socket: '/tmp/mysql.sock'
  
test:
  # Sqlite Settings
  adapter: jdbcmysql
  database: db/development.sqlite3_test
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_development
  # username: root
  # password:
  # pool: 5

production:
  # Sqlite Settings
  adapter: jdbcmysql
  database: db/development.sqlite3_production
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_development
  # username: root
  # password:
  # pool: 5

