basics: &basics
  site_name: Rate Marina's Outfits
  admin_email: marina@anachromystic.com

development: &non_production_settings
  <<: *basics
  site_url: http://localhost:3000
  
test:
  <<: *non_production_settings

staging:
  <<: *basics
  site_url: http://staging.example.com
  
production:
  <<: *basics
  site_url: http://marina.anachromystic.com/
